# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.user_locale_responselistener: 
        class: AppBundle\EventListener\LocaleListener
        arguments: [%kernel.default_locale%]
        tags:
            - { name: kernel.event_subscriber }
    app.user_locale_listener:
        class: AppBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method:onInteractiveLogin }
    app.utils.utils:
        class: AppBundle\Utils\Services\Utils
        arguments: ['@service_container']
    site.twig.reflectionExtension:
        class: AppBundle\Twig\Extension\Reflection
        tags:
            - { name: twig.extension }
    site.type.comment:
        class: AppBundle\Form\CommentType
        tags:
            - { name: form.type }
        arguments: ['@doctrine', '@request_stack']
    site.type.note:
        class: AppBundle\Form\NoteType
        tags:
            - { name: form.type }
        arguments: ['@doctrine', '@request_stack', '@translator']
    site.type.book:
        class: AppBundle\Form\BookType
        tags:
            - { name: form.type }
        arguments: ['@doctrine', '@request_stack', '@logger', '@translator']
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    fos_user.listener.email_confirmation:
        class: AppBundle\EventListener\EmailConfirmationListener
        arguments: ["@fos_user.mailer", "@fos_user.util.token_generator", "@router", "@session", '@service_container']
        tags:
            - { name: kernel.event_subscriber }