<?php

namespace AppBundle\Entity;
/**
 * CommentRepository
 *
 * This is the repository for the "Comment" entities.
 * 
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @author Eric COURTIAL
 * 
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository {
    
}
