<?php

namespace AppBundle\Entity;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * KindRepository
 *
 * This is the repository for the "Kind" entities.
 * 
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @author Eric COURTIAL
 * 
 */
class KindRepository extends \Doctrine\ORM\EntityRepository { 
    
    /**
     * 
     * Return the most productives kinds.
     * 
     * @param int $intQty : the max number of results returned.
     * @return mixed array of array, each one containing id and name 
     * of the kind. 
     * @throws \ErrorException
     * @throws NoResultException
     * 
     * @author Eric COURTIAL
     *
     */
    public function findByTopKinds($intQty) {
        
         $strQuery = $this->getEntityManager()->createQuery(
                'SELECT COUNT( a.id ) AS qty_occurences, 
                a.id,
                a.name
                FROM AppBundle:Kind a
                JOIN a.book b
                GROUP BY a.id'
            )
            ->setMaxResults($intQty);
        
        try {
            $arrQueryResults = $strQuery->getResult();
        } catch (Exception $exception) {
            throw $exception;
        }

        // The SQL request must return at least one result
        if(count($arrQueryResults) == 0) {
            throw new NoResultException;
        }

        return $arrQueryResults;
        
    }
    
    /**
     * 
     * Return all the kinds sorted by surname.
     * 
     * @param int $intPage is the number of the page of results
     * @return mixed array of kind entity. 
     * @throws \ErrorException
     * @throws NoResultException
     * 
     * @author Eric COURTIAL
     *
     */
    public function findAllOrderedByName($intPage = 1) {
        
        $intRefValue = Kind::QTY_KINDS;
        
        if($intPage > 1) {
            $intStart = (($intPage - 1) * $intRefValue);
            $intEnd = $intStart + $intRefValue - 1;
        } else {
            $intStart = 0;
            $intEnd = $intRefValue - 1;
        }
        
        $strQuery = $this->createQueryBuilder('p')
            ->setFirstResult($intStart)
            ->setMaxResults($intRefValue)
            ->orderBy('p.name', 'ASC');
        
        try {
            $arrQueryResults = new Paginator($strQuery);
        } catch (Exception $exception) {
            throw $exception;
        }

        // The SQL request must return at least one result
        if(count($arrQueryResults) == 0) {
            throw new NoResultException;
        }

        return $arrQueryResults;
        
    }
    
    /**
     * 
     * Return all the kinds sorted by name, but WITHOUT pagination.
     * 
     * @param int $intPage is the number of the page of results
     * @return mixed array of Kind entity. 
     * @throws \ErrorException
     * @throws NoResultException
     * 
     * @author Eric COURTIAL
     *
     */
    public function findAllOrderedByNameWp() {
        
        $strQuery = $this->createQueryBuilder('p')
            ->orderBy('p.name', 'ASC')
            ->getQuery();
        
        try {
            $arrQueryResults = $strQuery->getResult();
        } catch (Exception $exception) {
            throw $exception;
        }

        // The SQL request must return at least one result
        if(count($arrQueryResults) == 0) {
            throw new NoResultException;
        }

        return $arrQueryResults;
        
    }
    
    /**
     * 
     * search for kinds by surname.
     *
     * @param string $strName is the occurence to look for
     * @param int $intPage is the number of the page of results
     * @return mixed array of Kind entity. 
     * @throws \ErrorException
     * @throws NoResultException
     * 
     * @author Eric COURTIAL
     *
     */
    public function searchByName($strName, $intPage = 1) {

        $intRefValue = Kind::QTY_KINDS;
        
        if($intPage > 1) {
            $intStart = (($intPage - 1) * $intRefValue);
            $intEnd = $intStart + $intRefValue - 1;
        } else {
            $intStart = 0;
            $intEnd = $intRefValue - 1;
        }
        
        $strQuery = $this->createQueryBuilder('p')
            ->Where('p.name LIKE :Request')
            ->setFirstResult($intStart)
            ->setMaxResults($intRefValue)
            ->setParameter('Request', "%$strName%");
        
        try {
            $arrQueryResults = new Paginator($strQuery);
        } catch (Exception $exception) {
            throw $exception;
        }

        // The SQL request must return at least one result
        if(count($arrQueryResults) == 0) {
            throw new NoResultException;
        }

        return $arrQueryResults;
        
    }
    
    /**
     * Remove all the elements regarding one specific book
     * in the join table 
     * 
     * @param type $intBookId is the id of the book
     * @throws \AppBundle\Entity\Exception
     * 
     * @author Eric COURTIAL
     */
    public function removeByBookId($intBookId) {

        try {
            $query = $this->getEntityManager()->getConnection()->prepare('DELETE FROM myx_is_kind WHERE book_id = :id');
            $query->execute(array('id' => $intBookId));
        } catch (Exception $exception) {
            throw $exception;
        }
        
    }
    
}