<?php

namespace AppBundle\Entity;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends \Doctrine\ORM\EntityRepository {
    /**
     * 
     * Return all the languages sorted by name.
     * 
     * @param int $intPage is the number of the page of results
     * @return mixed array of Language entity. 
     * @throws \ErrorException
     * @throws NoResultException
     * 
     * @author Eric COURTIAL
     *
     */
    public function findAllOrderedByName($intPage = 1) {
        
        $intRefValue = Language::QTY_LANGUAGES;
        
        if($intPage > 1) {
            $intStart = (($intPage - 1) * $intRefValue);
            $intEnd = $intStart + $intRefValue - 1;
        } else {
            $intStart = 0;
            $intEnd = $intRefValue - 1;
        }
        
        $strQuery = $this->createQueryBuilder('p')
            ->setFirstResult($intStart)
            ->setMaxResults($intRefValue)
            ->orderBy('p.name', 'ASC');
        
        try {
            $arrQueryResults = new Paginator($strQuery);
        } catch (Exception $exception) {
            throw $exception;
        }

        // The SQL request must return at least one result
        if(count($arrQueryResults) == 0) {
            throw new NoResultException;
        }

        return $arrQueryResults;
        
    }
    
    /**
     * 
     * Return all the languages sorted by name, but WITHOUT pagination.
     * 
     * @param int $intPage is the number of the page of results
     * @return mixed array of Format entity. 
     * @throws \ErrorException
     * @throws NoResultException
     * 
     * @author Eric COURTIAL
     *
     */
    public function findAllOrderedByNameWp() {
        
        $strQuery = $this->createQueryBuilder('p')
            ->orderBy('p.name', 'ASC')
            ->getQuery();
        
        try {
            $arrQueryResults = $strQuery->getResult();
        } catch (Exception $exception) {
            throw $exception;
        }

        // The SQL request must return at least one result
        if(count($arrQueryResults) == 0) {
            throw new NoResultException;
        }

        return $arrQueryResults;
        
    }
    
    /**
     * 
     * search for languages by name.
     *
     * @param string $strName is the occurence to look for
     * @param int $intPage is the number of the page of results
     * @return mixed array of Language entity. 
     * @throws \ErrorException
     * @throws NoResultException
     * 
     * @author Eric COURTIAL
     *
     */
    public function searchByName($strName, $intPage = 1) {

        $intRefValue = Language::QTY_LANGUAGES;
        
        if($intPage > 1) {
            $intStart = (($intPage - 1) * $intRefValue);
            $intEnd = $intStart + $intRefValue - 1;
        } else {
            $intStart = 0;
            $intEnd = $intRefValue - 1;
        }
        
        $strQuery = $this->createQueryBuilder('p')
            ->Where('p.name LIKE :Request')
            ->setFirstResult($intStart)
            ->setMaxResults($intRefValue)
            ->setParameter('Request', "%$strName%");
        
        try {
            $arrQueryResults = new Paginator($strQuery);
        } catch (Exception $exception) {
            throw $exception;
        }

        // The SQL request must return at least one result
        if(count($arrQueryResults) == 0) {
            throw new NoResultException;
        }

        return $arrQueryResults;
        
    }
}
