<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\NoResultException;

/**
 * MaterialRepository
 *
 * This is the repository for the "Material" entities.
 * 
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @author Eric COURTIAL
 */
class MaterialRepository extends \Doctrine\ORM\EntityRepository {
    
    /**
     * 
     * Return all the materials sorted by name, but WITHOUT pagination.
     * 
     * @param int $intPage is the number of the page of results
     * @return mixed array of Material entity. 
     * @throws \ErrorException
     * @throws NoResultException
     * 
     * @author Eric COURTIAL
     *
     */
    public function findAllOrderedByNameWp() {
        
        $strQuery = $this->createQueryBuilder('p')
            ->orderBy('p.name', 'ASC')
            ->getQuery();
        
        try {
            $arrQueryResults = $strQuery->getResult();
        } catch (Exception $exception) {
            throw $exception;
        }

        // The SQL request must return at least one result
        if(count($arrQueryResults) == 0) {
            throw new NoResultException;
        }

        return $arrQueryResults; 
    }
}
