<?php

namespace AppBundle\Entity;
use Doctrine\ORM\NoResultException;

/**
 * UserRepository
 *
 * This the repository for the "User" entity.
 * 
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @author Eric COURTIAL
 */
class UserRepository extends \Doctrine\ORM\EntityRepository {
    
    /**
     * 
     * @param int $intQty is the max number of results wanted
     * @return array of array containing qty_occurences, user_id, 
     * user_name and user_surname.
     * @throws \AppBundle\Entity\Exception
     * @throws NoResultException
     * @author Eric COURTIAL
     */
    public function findByTopContributors($intQty) {
        
         $strQuery = $this->getEntityManager()->createQuery(
                'SELECT COUNT( b.user ) AS qty_occurences,
                IDENTITY(b.user) AS user_id,
                u.name AS user_name,
                u.surname AS user_surname
                FROM AppBundle:Book b, AppBundle:User u
                WHERE b.user = u.id
                GROUP BY b.user
                ORDER BY qty_occurences DESC'
            )
            ->setMaxResults($intQty);
        
        try {
            $arrQueryResults = $strQuery->getResult();
        } catch (Exception $exception) {
            throw $exception;
        }

        // The SQL request must return at least one result
        if(count($arrQueryResults) == 0) {
            throw new NoResultException;
        }

        return $arrQueryResults;
        
    }
    
}
